---
# PFC config
pfc_remote_path: /opt/acnodal/bin
pfc_interface: "{{ lookup('env', 'EPIC_PFC_INTF') | default('enp1s0', True) }}"

# Bird config
bird_remote_path: /opt/acnodal/bird

# k8s configuration
pod_cidr: "10.212.0.0/16"

extra_docker_config: ""

ansible_user: adamd

# purelb configuration

subnet: "192.168.66.0/24"
pool: "192.168.66.1-192.168.66.10"

# artifacts that we download from Gitlab

# ci-main-b02050fb
web_service_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fegw-web-service/jobs/1059521273/artifacts

# v0.5.3-xds7
resource_model_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fegw-resource-model/jobs/1088095996/artifacts

# v0.7.7
pfc_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fpacket-forwarding-component/jobs/1051082664/artifacts/pkg/pfc.tar.bz2

# "latest"
epicctl_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fepicctl/jobs/artifacts/main/raw/epicctl?job=build

endpoints_image: "{{ lookup('env', 'EPIC_XD_IMG') | default('registry.gitlab.com/acnodal/xds-operator:tls-bb88063f', True) }}"

envoy_image: "{{ lookup('env', 'EPIC_EP_IMG') | default('registry.gitlab.com/acnodal/envoy-for-egw:ci-eds-fbdbefaf', True) }}"
