---
# TRUE_INGRESS config
true_ingress_remote_path: /opt/acnodal/bin
true_ingress_interface: "{{ lookup('env', 'EPIC_TRUE_INGRESS_INTF') | default('enp1s0', True) }}"

# Bird config
bird_remote_path: /opt/acnodal/bird

ansible_user: adamd

# optional private registry (for development)
private_registry: "{{ lookup('env', 'EPIC_PRIVATE_REGISTRY') }}"

# kubeadm  init parameters

pod_cidr: "172.20.0.0/16"
svc_cidr: "172.21.0.0/16"

# flannel configuration

cni_network: "172.20.0.0/16"

# Web Service

ws_hostname: epic-ctl

# Images

marin3r_version: v0.10.0-epic3
marin3r_image: "registry.gitlab.com/acnodal/epic/marin3r:{{ marin3r_version }}"
eds_image: registry.gitlab.com/acnodal/epic/eds-server:v0.1.15
envoy_image: registry.gitlab.com/acnodal/epic/envoy:v0.5.1

# ServicePrefix values

service_prefix_name: default
service_prefix_subnet: 192.168.77.0/24
service_prefix_pool: 192.168.77.2-192.168.77.7
service_prefix_aggregation: "/32"

# PureLB values

purelb_subnet: 192.168.254.0/24
purelb_pool: 192.168.254.200-192.168.254.201
purelb_aggregation: "/32"

# LBServiceGroup values

group_org_name: root
group_org_ns: "epic-{{ group_org_name }}"

# public artifacts

certmanager_artifact: https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml

# Private artifacts that we download from Gitlab

# v0.19.1
resource_model_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fepic%2Fresource-model/packages/generic/manifest-package/v0.19.1/epic-resource-model.yaml

# v0.4.4
web_service_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fepic%2Fweb-service/packages/generic/manifest/v0.4.4/web-service.yaml

# v0.13.0
true_ingress_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fepic%2Ftrue-ingress/packages/generic/true-ingress/v0.13.0/true-ingress.tar.bz2

# v0.7.0
epicctl_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fepic%2Fepicctl/packages/generic/epicctl/v0.7.0/epicctl

# v0.7.0
epicctl_scanlogs_artifact: https://gitlab.com/api/v4/projects/acnodal%2Fepic%2Fepicctl/packages/generic/epicctl/v0.7.0/scan-logs

marin3r_artifact: "https://gitlab.com/api/v4/projects/acnodal%2Fepic%2Fmarin3r/packages/generic/manifest/{{ marin3r_version }}/marin3r-manifest-epic.yaml"

contour_artifact: https://charts.bitnami.com/bitnami/contour-7.0.6.tgz
