 
egw:
  hosts:
    192.168.151.163:

# multus bridge net-attach-def

      bridge_name: multus0
      isGateway: true
      subnet: "192.168.102.0/24"
      rangeStart: "192.168.102.200"
      rangeEnd: "192.168.102.216"
      gateway: "192.168.102.1"



# k8s configuration

      pod_cidr: "10.246.0.0/16"

  vars:
    gitlab_user: "oz_adam"
    gitlab_secret: "Qi4oXVKA1gzGdenTCd7G"
    postgresql_egw_user: egw
    postgresql_egw_password: 18companyOTHERbornSOON
    database_ip: '192.168.1.40'
