---
epic:
  hosts:
    # variable default values are defined in group_var/epic.yaml,
    # overrides go here

    192.168.10.43:


            k8s_ipaddr: "192.168.10.43"
            k8s_nic: "ens4"
            k8s_cluster_vip: "192.168.10.25"

# kubeadm  init parameters

            pod_cidr: "172.20.0.0/16,fd01::/64"
            svc_cidr: "172.21.0.0/16,fd02::/112"



# haproxy & keepalived

                  


# flannel configuration

            cni_network: "172.20.0.0/16"
            cni_IPv6network: "fd01::/64" 
