 
egw:
  hosts:
    192.168.151.160:

# ipvlan configuration

      master_int: enp1s0
      subnet: "192.168.101.0/24"
      rangeStart: "192.168.101.200"
      rangeEnd: "192.168.151.216"
      gateway: "192.168.101.1"



# k8s configuration

      pod_cidr: "10.245.0.0/16"
  
  vars:
    gitlab_user: "oz_adam"
    gitlab_secret: "Qi4oXVKA1gzGdenTCd7G"
