---
# variable default values are defined in group_vars/epic.yaml,
# overrides go here
epic:
  hosts:
    epic1: # the first epic host in an acndev cluster, usually 192.168.254.11
      ansible_user: vagrant
      k8s_ipaddr: 192.168.254.11
      k8s_nic: eth1
      k8s_cluster_vip: 192.168.254.11
      true_ingress_interface: eth1
      ws_hostname: acndev-ctl

    192.168.10.50:

      k8s_ipaddr: 192.168.10.50
      k8s_nic: "ens4"
      k8s_cluster_vip: "192.168.10.25"

      # kubeadm  init parameters
      pod_cidr: "172.20.0.0/16,fd01::/60"
      svc_cidr: "172.21.0.0/16,fd02::/112"

      # flannel configuration
      cni_network: "172.20.0.0/16"
      cni_IPv6network: "fd01::/60"
client:
  hosts:
    mk8s1: # the first client host in an acndev cluster, usually 192.168.254.101
      ansible_user: vagrant
      k8s_ipaddr: 192.168.254.101
      k8s_nic: eth1
      k8s_cluster_vip: 192.168.254.101
      true_ingress_interface: eth1
