---
# variable default values are defined in group_vars/epic.yaml,
# overrides go here
epic:
  hosts:
    epic1: # the first epic host in an acndev cluster, usually 192.168.254.11
      k8s_cluster_vip: 192.168.254.11
      true_ingress_interface: eth1
      ws_hostname: acndev-ctl

    192.168.10.50:
      ansible_user: adamd
      k8s_nic: ens4
      k8s_cluster_vip: "192.168.10.25"
client:
  hosts:
    mk8s1: # the first client host in an acndev cluster, usually 192.168.254.101,fd00:254::101
      k8s_nodeaddr: 192.168.254.101,fd00:254::101
      # kubeadm init parameters
      pod_cidr: 172.23.0.0/16,fd03::/60
      svc_cidr: 172.24.0.0/16,fd04::/112
      # flannel configuration
      cni_network: 172.23.0.0/16
      cni_IPv6network: fd03::/60
node:
  hosts:
    mk8s2:
      k8s_nodeaddr: 192.168.254.102,fd00:254::102
    mk8s3:
      k8s_nodeaddr: 192.168.254.103,fd00:254::103
