---
egw:
  hosts:
    # variable default values are defined in group_var/egw.yaml,
    # overrides go here
    192.168.122.12:
      pfc_interface: ens3
    192.168.122.240:
      pfc_interface: ens3

    192.168.151.128:
