#  Install Containerd

- name: install containerd
  apt:
    name:
    - containerd

- name: create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: create containerd defaults
  shell: containerd config default > /etc/containerd/config.toml

- name: update systemd cgroup in /etc/containerd/config.toml
  replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup.*'
    replace: '\1SystemdCgroup = true'

- name: enable development registry
  blockinfile:
    path: /etc/containerd/config.toml
    insertafter: \[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    block: |
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ private_registry }}"]
      endpoint = ["http://{{ private_registry }}"]
  when: private_registry != ""

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
