#  Install Containerd

- name: install containerd
  apt:
    name: 
    - containerd
  become: true

- name: create containerd config directory
  file:
    path: /etc/containerd 
    state: directory
    mode: '0755'

- name: create containerd defaults
  shell: containerd config default > /etc/containerd/config.toml

- name: update systemd cgroup in /etc/containerd/config.toml
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup'
    line: SystemdCgroup = true


- name: restart containerd
  systemd:
    name: containerd
    state: restarted