#  Install Containerd

- name: install containerd
  apt:
    name: 
    - containerd
  become: true

- name: create containerd config directory
  file:
    path: /etc/containerd 
    state: directory
    mode: '0755'

- name: create containerd defaults
  command: containerd config default > /etc/containerd/config.toml

- name: restart containerd
  systemd:
    name: containerd
    state: restarted