---

- name: check dependencies installed
  apt:
    update_cache: yes
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - ipvsadm
    install_recommends: no
  become: true

- name: get gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: copy repo file
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes
  become: true

- name: install k8s executables
  apt:
    update_cache: yes
    name:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: install python client libraries
  # I'd rather use the debian/ubuntu package but it's way too old
  command: pip3 install kubernetes~=12.0
  become: true

- name: mark for version hold
  shell: apt-mark hold kubelet kubeadm kubectl
  become: true

- name: create kubernetes manifests directory
  file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: '0755'
  become: true
