---
# tasks file for epic
- name: Pull in the secrets
  include_vars: files/vault.yml
  no_log: true

- name: install acnodal CLI tools
  block:
  - name: create acnodal installation directory
    file:
      path: "{{ true_ingress_remote_path }}"
      state: directory
      mode: ugo+rx
  - include_tasks: true_ingress.yml
  - include_tasks: epicctl.yml
  become: true

- include_tasks: k8s-install.yml

- name: Fetch the EPIC admin kubeconfig # so we can use kubectl from the host
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: epic-admin.conf
    flat: yes
  become: true

- name: reset any persistent namespace that we might have set
  command: kubectl config set-context --current --namespace=
  become: true

- include_tasks: multus-install.yml
- include_tasks: router-install.yml
  args: {apply: {become: true}}
- include_tasks: cert-manager-install.yml
- include_tasks: marin3r-install.yml

- include_tasks: resource-model.yml
  tags: [ lbsg ]
- include_tasks: gwsm.yml
- include_tasks: web-service-install.yml
- include_tasks: purelb.yml
- include_tasks: contour-ingress.yml
- include_tasks: setup-daemon.yml
  args: {apply: {become: true}}
