---
- name:  create namespace
  command: kubectl create namespace marin3r-system
  register: result
  failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

- name: create secret for acnodal private registry
  command: kubectl -n marin3r-system create secret docker-registry gitlab --docker-server=registry.gitlab.com --docker-username={{gitlab_user}} --docker-password={{gitlab_secret}}
  no_log: true
  register: result
  failed_when: result.rc != 0 and "already exists" not in result.stderr

- name: Upload manifest
  template:
    src: files/marin3r-manifest.yml
    dest: marin3r-manifest.yml

- name: Apply manifest, not overriding the marin3r image
  when: marin3r_image is not defined
  command: kubectl apply -f marin3r-manifest.yml
