---
- name: Upload manifest
  template:
    src: files/marin3r-manifest.yml
    dest: marin3r-manifest.yml


- name: Apply manifest, not overriding the marin3r image
  when: marin3r_image is not defined
  command: kubectl apply -f marin3r-manifest.yml
