---
- name: Upload manifest
  template:
    src: files/marin3r-manifest.yml
    dest: marin3r-manifest.yml

- name: Apply manifest, overriding the marin3r image if the override variable is set
  when: marin3r_image is defined
  shell: cat marin3r-manifest.yml | sed "s~quay.io/3scale/marin3r:v0.7.0~{{ marin3r_image }}~" | kubectl apply -f -

- name: Apply manifest, not overriding the marin3r image
  when: marin3r_image is not defined
  command: kubectl apply -f marin3r-manifest.yml
