---

- name:  (multus-install.yml) transfer multus yaml
  copy:
    src: files/multus-daemonset.yml
    dest: multus-daemonset.yml
- name:  Apply multus daemonset
  command: kubectl apply -f multus-daemonset.yml

- name: create multus namespace
  command: kubectl create namespace multus
  register: result
  failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

