---
- name: copy sysctl file
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: copy modules file
  copy:
    src: files/k8s-modules.conf
    dest: /etc/modules-load.d/k8s.conf

- name: update sysctl
  command: /sbin/sysctl --system

- name: run modprobe
  command: /usr/sbin/modprobe br_netfilter

- name: disable swap
  command: /sbin/swapoff -a

- name: edit fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent

- name: install system tools
  apt:
    update_cache: yes
    name:
    - ipset
    - linux-tools-common
    - acl
    - jq
    - bridge-utils
    - python3-pip
    - unzip
    install_recommends: no



- name: set up system-wide environment variables
  copy:
    dest: /etc/environment
    mode: ugo+r
    content: |
      PATH="{{ true_ingress_remote_path }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      KUBECONFIG="/etc/kubernetes/admin.conf"

- name: add me to some useful groups
  user:
    name: '{{ ansible_user }}'
    groups:
    - systemd-journal
    - root
    append: yes
- name: Reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
