---
- name: create bird config directory
  file:
    path: "{{ bird_remote_path }}"
    state: directory
    mode: ugo+rx

- name:  create router namespace
  command: kubectl create namespace router
  register: result
  failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

- name: create secret for acnodal private registry
  command: kubectl -n router create secret docker-registry gitlab --docker-server=registry.gitlab.com --docker-username={{gitlab_user}} --docker-password={{gitlab_secret}}
  no_log: true
  register: result
  failed_when: result.rc != 0 and "already exists" not in result.stderr

- name: copy bird configmap
  copy:
    src: files/bird-cm.yml
    dest: bird-cm.yml
    
- name: apply bird configmap
  command: kubectl apply -f bird-cm.yml

- name: create bird configuration
  copy:
    src: files/bird-epic.yml
    dest: bird-epic.yml

- name: create router - bird deployment
  command: kubectl apply -f bird-epic.yml
