---
- name: download manifest from gitlab
  get_url:
    headers:
      PRIVATE-TOKEN: "{{ gitlab_toby_ansible_ro }}"
    url: "{{ web_service_artifact }}"
    dest: ./

- name: unzip artifacts
  unarchive:
    src: artifacts.zip
    remote_src: yes
    dest: ./

- name: override docker image if EPIC_WS_IMG is set
  when: lookup('env', 'EPIC_WS_IMG') != ""
  shell:
    cmd: sed "s registry.gitlab.com/acnodal/epic/web-service:unknown {{ lookup('env', 'EPIC_WS_IMG') }} " < config/web-service.yaml > deploy/web-service.yaml
    warn: no

- name:  Launch web service
  shell: kubectl apply -f deploy/web-service.yaml
