---
# tasks file for client worker nodes

- include_tasks: osprepk8s.yml
  args: {apply: {become: true}}
- include_tasks: containerd-install.yml
  args: {apply: {become: true}}
- include_tasks: kube-clients-install.yml
  args: {apply: {become: true}}

- name: Wait for the controlplane playbook to write the join script
  local_action:
    module: wait_for
    path: "{{ join_script }}"
- name: upload cluster join script
  copy:
    src: "{{ join_script }}"
    dest: /root
    mode: +x
  become: yes
- name: Join the cluster
  shell:
    cmd: "/root/{{ join_script }}"
    creates: /etc/kubernetes/kubelet.conf
  become: yes
  retries: 3
  delay: 30
  register: result
  until: result is not failed
- name: allow users in the root group to use kubelet.conf
  shell:
    cmd: chmod --recursive ug+r /etc/kubernetes/kubelet.conf /var/lib/kubelet
    warn: false
  become: yes
- name: allow users in the root group to use kubelet.conf
  shell:
    cmd: chmod ug+rx /var/lib/kubelet /var/lib/kubelet/pki
    warn: false
  become: yes
- name: Wait for the node to become ready
  command: kubectl --kubeconfig=/etc/kubernetes/kubelet.conf wait --for=condition=ready --timeout=5m node/{{ ansible_hostname }}
