---
- name: install cert-manager which the egw operator webhook needs
  # https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests
  command: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.3/cert-manager.yaml

- name: Wait for cert manager to be ready so marin3r will load
  # marin3r requires that cert-manager's webhooks be operational but
  # that takes a few seconds so we need to explicitly wait
  command: kubectl wait --for=condition=Ready --timeout=5m -n cert-manager pods --all
