---
- name: Load EGW custom resource definitions and samples
  block:
    - name: Create EGW namespace
      shell: "curl -s --header \"PRIVATE-TOKEN: {{ gitlab_toby_ansible_ro }}\" {{ job }}/config/crd/egw-namespace.yaml | kubectl apply -f -"
      args:
        warn: false
      register: result
      failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

    - name: Apply EGW custom resource definitions
      shell: "curl -s --header \"PRIVATE-TOKEN: {{ gitlab_toby_ansible_ro }}\" {{ job }}/config/crd/bases/egw.acnodal.io.yaml | kubectl apply -f -"
      args:
        warn: false

    - name: Create sample namespace
      shell: "curl -s --header \"PRIVATE-TOKEN: {{ gitlab_toby_ansible_ro }}\" {{ job }}/config/samples/namespace.yaml | kubectl apply -f -"
      args:
        warn: false
      register: result
      failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

    - name: Create sample account
      shell: "curl -s --header \"PRIVATE-TOKEN: {{ gitlab_toby_ansible_ro }}\" {{ job }}/config/samples/egw_v1_account.yaml | kubectl apply -f -"
      args:
        warn: false

    - name: Create sample service group
      shell: "curl -s --header \"PRIVATE-TOKEN: {{ gitlab_toby_ansible_ro }}\" {{ job }}/config/samples/egw_v1_servicegroup.yaml | kubectl apply -f -"
      args:
        warn: false

  vars:
    job: https://gitlab.com/api/v4/projects/21452659/jobs/786298464/artifacts # this is egw-resource-model v0.1.1-pre1
