---
- name: Pull in the secrets
  include_vars: files/vault.yml
  no_log: true

- name: Apply EGW custom resource definitions
  #                                                                        this is v0.1.0-pre2
  shell: "curl -s --header \"PRIVATE-TOKEN: {{ gitlab_toby_ansible_ro }}\" https://gitlab.com/api/v4/projects/21452659/jobs/766728496/artifacts/config/crd/bases/egw.acnodal.io.yaml | kubectl apply -f -"
  args:
    warn: false
