---
- name: download epicctl CLI from gitlab
  get_url:
    url: "{{ epicctl_artifact }}"
    dest: "{{ pfc_remote_path }}"
    mode: +x
    headers:
      PRIVATE-TOKEN: "{{ gitlab_toby_ansible_ro }}"
