---
- name: create k8s config file
  template:
    src: kubeinit.j2
    dest: /root/egw.conf
  become: yes
- name: install kubernetes
  command: kubeadm init --config /root/egw.conf
  become: yes
  args:
    creates: /etc/kubernetes/pki/ca.key


# We do this taint/untaint dance because "taint --overwrite" is
# idempotent so this pair of commands will work on new clusters and
# also work when we're updating an existing cluster
- name: taint controller
  command: kubectl taint nodes --all --overwrite node-role.kubernetes.io/master:NoSchedule
- name: untaint controller
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/master-
  become: yes

- name: create local flannel.yml
  template:
    src: kube-flannel.j2
    dest: /root/kube-flannel.yml
  become: yes

- name: add flannel - K8s CNI
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /root/kube-flannel.yml
  become: yes

- name: copy OpenEBS file
  copy:
    src: files/openebs-operator.yaml
    dest: /root/openebs-operator.yml
  become: yes

- name: copy OpenEBS default jiva storage class
  copy:
    src: files/update-jiva-sc.yml
    dest: /root/update-jiva-sc.yml
  become: yes

- name: Add OpenEBS - Persistant Storage System
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /root/openebs-operator.yml
  become: yes

- name: update Jiva default storage class
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /root/update-jiva-sc.yml
  become: yes

