---

- name: idenify if k8s is installed
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_installed


- name: clear previous k8s installation if present
  block:
    - name:  drain node
      shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf drain {{ansible_nodename}} --delete-local-data --force --ignore-daemonsets
    - name: delete node
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf delete node {{ansible_nodename }}
    - name:  reset kubadm
      command: kubeadm reset -f
  when: k8s_installed.stat.exists
  become: yes


- name: create k8s config file
  template:
    src: kubeinit.j2
    dest: /root/egw.conf
  become: yes

- name: install kubernetes
  command: kubeadm init --config /root/egw.conf
  become: yes

- name: untaint controller
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/master-
  become: yes

- name: create local flannel.yml
  template:
    src: kube-flannel.j2
    dest: /root/kube-flannel.yml
  become: yes

- name: add flannel
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /root/kube-flannel.yml
  become: yes

