---

- name: check dependencies installed
  apt:
    update_cache: yes
    name:
    - apt-transport-https
    - curl
    - ipvsadm
    install_recommends: no
  become: yes

- name: get gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes

- name: copy repo file
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes
  become: yes

- name: install k8s executables
  apt:
    update_cache: yes
    name:
    - kubelet
    - kubeadm
    - kubectl
  become: yes

- name: install python client libraries
  # I'd rather use the debian/ubuntu package but it's way too old
  command: pip3 install kubernetes~=12.0
  become: yes

- name: mark for version hold
  shell: apt-mark hold kubelet kubeadm kubectl
  become: yes

- name: add kubens
  copy:
    src: files/kubens
    dest: /usr/local/bin/kubens
    mode: '0755'
  become: yes

- name: upload kustomize install script
  copy:
    src: files/install_kustomize.sh
    dest: /root
    mode: '0755'
  become: yes
- name: install kustomize
  command:
    cmd: /root/install_kustomize.sh 3.8.6
    chdir: /usr/local/bin
    creates: /usr/local/bin/kustomize
  become: yes
