---
# tasks file for egw

- name: Figure out the name of the user running on the target
  command: whoami
  register: target_user

- name: Pull in the secrets
  include_vars: files/vault.yml
  no_log: true

- include_tasks: osprepk8s.yml
  args:
    apply:
      become: yes
- include_tasks: docker-install.yml
- include_tasks: kube-clients-install.yml
- include_tasks: k8s-install.yml

- name: Fetch the EGW admin kubeconfig # so we can use kubectl from the host
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: egw-admin.conf
    flat: yes
  become: yes

- include_tasks: multus-install.yml
- include_tasks: router-install.yml
- include_tasks: cert-manager-install.yml

- include_tasks: egw-data-model.yml
- include_tasks: egw-operators.yml
- include_tasks: web-service-install.yml
