---
# tasks file for egw

- name: Figure out the name of the user running on the target
  command: whoami
  register: target_user

- name: Pull in the secrets
  include_vars: files/vault.yml
  no_log: true

- include_tasks: osprepk8s.yml
- include_tasks: pfc.yml
- include_tasks: docker-install.yml
- include_tasks: kube-clients-install.yml
- include_tasks: k8s-install.yml

- name: Fetch the EGW admin kubeconfig # so we can use kubectl from the host
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: egw-admin.conf
    flat: yes
  become: yes

- include_tasks: multus-install.yml
- include_tasks: router-install.yml

- name:  Create acnodal namespace
  command: kubectl create namespace acnodal
  register: result
  failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

- include_tasks: egw-data-model.yml
- include_tasks: xds-operator.yml
- include_tasks: web-service-install.yml
