---

- name:  transfer multus yaml
  copy:
    src: files/multus-daemonset.yml
    dest: /root/multus-daemonset.yml
  become: yes

- name:  Apply multus daemonset
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /root/multus-daemonset.yml
  become: yes

- name: create net-attach-def
  template:
    src: net-attach-multus0.j2
    dest: /root/net-attach-multus0.yml
  become: yes

- name: create multus namespace
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create namespace multus
  become: yes
  ignore_errors: yes

- name: create net-attach-def multus0
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /root/net-attach-multus0.yml
  become: yes



