---
- name: copy sysctl file
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: update sysctl
  command: /sbin/sysctl --system

- name: disable swap
  command: /sbin/swapoff -a

- name: edit fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent

- name: install system tools
  apt:
    update_cache: yes
    name:
    - ipset
    - linux-tools-common
    - acl
    - open-iscsi
    - jq
    - bridge-utils
    install_recommends: no

- name: enable & start iscsi client
  systemd:
    name: iscsid
    state: started
    enabled: yes

- name: set up system-wide environment variables
  copy:
    dest: /etc/environment
    mode: ugo+r
    content: |
      PATH="{{ pfc_remote_path }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      KUBECONFIG="/etc/kubernetes/admin.conf"

- name: add me to some useful groups
  shell: "usermod -a -G systemd-journal,root {{ target_user.stdout }}"
- name: Reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection

- name: mount BPF filesystem
  mount:
    state: mounted
    fstype: bpf
    src: bpf
    path: /sys/fs/bpf
