---

- name: copy sysctl file
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  become: yes
  
- name: update sysctl
  command: /sbin/sysctl --system
  become: yes

- name: disable swap
  command: /sbin/swapoff -a
  become: yes

- name: edit fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
  become: yes

- name: install system tools
  apt:
    update_cache: yes
    name:
    - ipset
    - linux-tools-common
    - acl
    - open-iscsi
    - jq
    install_recommends: no
  become: yes
  
- name: enable & start iscsi client
  systemd:
    name: iscsid
    state: started
    enabled: yes
  become: yes

- name: add bash alises file to root
  copy:
    src: files/bash_aliases
    dest: /root/.bash_aliases
  become: yes
