---
- name: install the packet forwarding components
  become: yes
  block:
  - name: create installation directory
    file:
      path: "{{ pfc_remote_path }}"
      state: directory
      mode: ugo+rx

  - name: copy files
    copy:
      src: "{{ item }}"
      dest: "{{ pfc_remote_path }}/"
      mode: a+x
    with_fileglob:
      - "{{ pfc_src_path }}/src/*.o"
      - "{{ pfc_src_path }}/src/*.sh"
      - "{{ pfc_src_path }}/src/cli_cfg"
      - "{{ pfc_src_path }}/src/cli_service"
      - "{{ pfc_src_path }}/src/cli_tunnel"
      - "{{ pfc_src_path }}/src/cli_gc"
      - "{{ pfc_src_path }}/test/port_*.sh"
      - "{{ pfc_src_path }}/test/pfc_*.sh"
      - "{{ pfc_src_path }}/test/docker/gue_ping_svc_auto"
      - "{{ pfc_src_path }}/src/go/pfc_cli_go"

  - name: mount BPF filesystem
    mount:
      state: mounted
      fstype: bpf
      src: bpf
      path: /sys/fs/bpf
