---
- name: download PFC artifacts from gitlab
  get_url:
    headers:
      PRIVATE-TOKEN: "{{ gitlab_toby_ansible_ro }}"
    url: "{{ pfc_artifact }}"
    dest: /root
- name: untar artifacts
  unarchive:
    src: /root/pfc.tar.bz2
    dest: "{{ pfc_remote_path }}"
    extra_opts:
    - --strip-components=1
    remote_src: yes

- name: mount BPF filesystem
  mount:
    state: mounted
    fstype: bpf
    src: bpf
    path: /sys/fs/bpf
