---
- name: create installation directory
  file:
    path: "{{ pfc_remote_path }}"
    state: directory
    mode: ugo+rx

- name: download PFC artifacts from gitlab
  get_url:
    headers:
      PRIVATE-TOKEN: "{{ gitlab_toby_ansible_ro }}"
    url: https://gitlab.com/api/v4/projects/acnodal%2Fpacket-forwarding-component/jobs/844061158/artifacts/pfc.tar.bz2 # v0.4.1
    dest: /root
- name: untar artifacts
  unarchive:
    src: /root/pfc.tar.bz2
    dest: "{{ pfc_remote_path }}"
    extra_opts:
    - --strip-components=1
    remote_src: yes

- name: mount BPF filesystem
  mount:
    state: mounted
    fstype: bpf
    src: bpf
    path: /sys/fs/bpf
