---
- name: Install postgresql packages
  apt:
    package: postgresql
  become: yes

- name: Tell postgresql to listen on *
  copy:
    dest: /etc/postgresql/12/main/conf.d/listen-on-all.conf
    owner: postgres
    group: postgres
    content: |
      # - Connection Settings -
      listen_addresses = '*'
  become: yes

- name: Allow egw to login to postgresql over the network
  copy:
    dest: /etc/postgresql/12/main/pg_hba.conf 
    owner: postgres
    group: postgres
    content: |
      # TYPE  DATABASE        USER            ADDRESS                 METHOD
      # "local" is for Unix domain socket connections only
      local   all             all                                     peer
      # IPv4 local connections:
      host    all             all             127.0.0.1/32            password
      # IPv6 local connections:
      host    all             all             ::1/128                 password

      host    sameuser        all             samenet                 password
  become: yes

- name: postgres_restart
  systemd:
    name: postgresql
    state: restarted
  become: yes

- name: find ip address of prefered int
  shell: "ip -br  -j addr show dev {{postgresql_pref_int}} | jq -r .[0].addr_info[0].local"
  register: database_ip



