---

- name: Install PureLB
  command: kubectl apply -f https://public:cCBr-URZKP-fFhAnWrZE@gitlab.com/api/v4/projects/20400619/packages/generic/manifest/0.0.1/purelb-complete.yaml
  retries: 3
  delay: 2
  register: result
  until: result.rc == 0

- name: create default service group
  template:
    src: purelbsg-default.j2
    dest: purelbsg-default.yml

- name: create default servicegroup
  command: kubectl apply -f purelbsg-default.yml
