---
- name: Pull in the secrets
  include_vars: files/vault.yml
  no_log: true

- name:  create router namespace
  command: kubectl create namespace router
  register: result
  failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

- name: create secret for acnodal private registry
  command: kubectl -n router create secret docker-registry gitlab --docker-server=registry.gitlab.com --docker-username={{gitlab_user}} --docker-password={{gitlab_secret}}
  register: result
  failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

- name: copy bird configmap
  copy:
    src: files/bird-cm.yml
    dest: bird-cm.yml
- name: apply bird configmap
  command: kubectl apply -f bird-cm.yml

- name: create bird configuration
  copy:
    src: files/bird-egw.yml
    dest: bird-egw.yml
- name: create router - bird deployment
  command: kubectl apply -f bird-egw.yml
