---
- name: create secret for acnodal private registry for acnodal namespace
  command: kubectl -n acnodal create secret docker-registry gitlab --docker-server=registry.gitlab.com --docker-username={{gitlab_user}} --docker-password={{gitlab_secret}}
  register: result
  failed_when: result.rc != 0 and "AlreadyExists" not in result.stderr

- name: Upload web service manifest
  template:
    src: templates/egw-ws-demo.yml.j2
    dest: egw-ws-demo.yml
- name:  Launch web service
  command: kubectl apply -f egw-ws-demo.yml
