---
- name: Upload web service manifest
  template:
    src: templates/egw-web-service.yml.j2
    dest: egw-web-service.yml
- name:  Launch web service
  command: kubectl apply -f egw-web-service.yml
