---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal
spec:
  selector:
    matchLabels:
      app: internal
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
      - name: internal
        image: mccutchen/go-httpbin
      topologySpreadConstraints:
      - topologyKey: kubernetes.io/hostname
        maxSkew: 1
        labelSelector:
          matchLabels:
            app: internal
        whenUnsatisfiable: ScheduleAnyway
---
kind: Service
apiVersion: v1
metadata:
  name: internal
spec:
  type: NodePort
  selector:
    app: internal
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: internal
spec:
  gatewayClassName: gwdev-http4
  listeners:
  - protocol: HTTP
    port: 80
    name: gwdev-web
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: internal-1
spec:
  parentRefs:
  - name: internal
  rules:
  - backendRefs:
    - name: internal
      port: 8080
