---
- name: check dependencies installed
  apt:
    update_cache: yes
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - ipvsadm
    install_recommends: no
  become: true

- name: get gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: copy repo file
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes
  become: true

- name: install k8s executables
  apt:
    name:
    - kubelet={{ k8s_version_apt }}
    - kubeadm={{ k8s_version_apt }}
    - kubectl={{ k8s_version_apt }}
  become: true
